[project]
name = "p1-rock-or-mine-pred"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy>=2.3.1",
    "pandas>=2.3.0",
    "sacred>=0.8.7",
    "scikit-learn>=1.7.0",
]
